version: "3.8"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${MEDIA_ROOT}:/data/media
    devices:
      - /dev/dri:/dev/dri
    tmpfs:
      - /transcode:size=8G

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${NORD_WG_PRIVATE_KEY}
      - SERVER_CITIES=${VPN_CITIES}
      - SERVER_COUNTRIES=${VPN_COUNTRIES}
      - FIREWALL=on
    volumes:
      - ${GLUETUN_CONFIG}:/gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORT=${QBIT_WEBUI_PORT}
    volumes:
      - ${QBIT_CONFIG}:/config
      - ${QBIT_DOWNLOADS}:/downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${TV_SHOWS_ROOT}:/tv 
      - ${DOWNLOADS_ROOT}:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${MOVIES_ROOT}:/movies 
      - ${DOWNLOADS_ROOT}:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_INTERVAL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG}:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${OVERSEERR_CONFIG}:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: bookshelf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BOOKSHELF_CONFIG}:/config
      - ${BOOKS_ROOT}:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BAZARR_CONFIG}:/config
      - ${MOVIES_ROOT}:/movies
      - ${TV_SHOWS_ROOT}:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${SABNZBD_CONFIG}:/config
      - ${USENET_DOWNLOADS}:/downloads
      - ${USENET_INCOMPLETE}:/incomplete-downloads